server:
  port: 8083
  servlet:
    context-path: /auth
    
spring:
  application:
    name: arq-oauth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/db-oauth?serverTimezone=America/Sao_Paulo
    username: root
    password: admin

security:
    jwt:
      token:
        secret-key: chave_microservices
        expire-length: 360000
  
     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka      
