server:
  port: 8081
  servlet:    context-path: /crud
    
spring:  application:    name: arq-crud  jpa:    show-sql: false
    hibernate:      ddl-auto: update
    properties:      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect  jmx:    enabled: false
  datasource:    url: jdbc:mysql://localhost:3306/db-crud?serverTimezone=America/Sao_Paulo
    username: root
    password: admin
    
  rabbitmq:    host: localhost
    port: 5672
    username: admin
    password: admin
    
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.product.routingkey
    
security:
    jwt:
      token:
        secret-key: chave_microservices
        expire-length: 360000
     
              
   
      